### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by Hedgehogues** [richard2259/dependencies-manager#2]
В Golang обычно тесты (юниты, функциональные) лежат рядом с пакетом, который они тестируют. Если это интеграционники -- тогда другое дело. В данном случае на интеграционники не очень похоже, это скорее всего функциональные тесты. Поэтому их логично положить рядом с проектом.

Директорию data, наверное, следует вынести в корень и держать там тестовые данные. Возможно, это стоит делать в поддиректории test.

Также, обрати внимание на пакет https://pkg.go.dev/github.com/stretchr/testify/require. С его помощью, твои тесты будут изящнее выглядеть. Например:

```
package test

import (
	manager "github.com/richard2259/dependencies-manager"
	"os"
	"testing"
        "github.com/stretchr/testify/require"
)

const numberOfServices int = 12

func TestParseYMLToDockerCompose(t *testing.T) {
	dockerCompose := manager.ParseYML(os.Getenv("TEST_DOCKER_COMPOSE_FILE_PATH"))
        require.NotEq(t, len(dockerCompose.Version), 0)
        require.NotEq(t, len(dockerCompose.Services), numberOfServices)
        dependsOn := dockerCompose.Services["database"].DependsOn
        require.Len(t, dependsOn, 0)
}
```

Также, не очень хорошей идеей является хардкодить число сервисов внутри теста. А что если у тебя файлик изменится. Тесты полетят. И глобальная переменная -- это тоже не самая клёвая идея. Самый лучший вариант -- это вытаскивать информацию из файлика.

**Comment by voidwalker8** [comment]
Tests refactored based on the aforementioned comments.
